### ISSUE TITLE
custom hitsound not working, renamed .wav file to "max.wav" and its not using it after restarting runelite

### ISSUE THREAD

**Issue by ShrrgWolf** [Hit-Sounds/hit-sounds#2]
![image](https://user-images.githubusercontent.com/38446510/194722788-42e7c795-48e4-4515-bcab-50e62dec721c.png)

**Comment by Ferrariic** [comment]
Can you send your client.log file and -- as well, send a pic of your configuration?

**Comment by Ferrariic** [comment]
Closing as it has been 7 days, feel free to comment to re-open.

**Comment by maximonster** [comment]
Came across this same issue. Managed to fix this by saving the WAV file as signed 16-bit PCM instead of 32-bit float PCM.
