### ISSUE TITLE
Hit Sounds Plugin not working, even using default options

### ISSUE THREAD

**Issue by Marstead** [Hit-Sounds/hit-sounds#4]
I've downloaded the Plugin, have it turned on and have all the default settings in place (I've used "Reset" to make that happen). But no hitsplat sounds have changed. Does this plugin have any known conflicts with other plugins?

**Comment by Ferrariic** [comment]
Please submit your client.log file, and your plugin configuration :) 

Additionally, make sure your in-game sounds are on!

What are your system specifications as well?

**Comment by Marstead** [comment]
[client_2022-10-14.0.log](https://github.com/Hit-Sounds/hit-sounds/files/9793386/client_2022-10-14.0.log)

![image](https://user-images.githubusercontent.com/54672873/196012898-1adcd5c5-7b8c-41a5-8bf0-ea90dad2bad7.png)

W10, game sounds are on, I hear the default sounds instead of the the specified sounds. Any other info I can pass along? Thanks!

**Comment by Ferrariic** [comment]
I think I know what you mean — I can't remove the default sounds unfortunately, it's a runelite/client constraint at this time. Can you try changing the normal hitsound to something like "Improved Reflexes" and let me know if you hear anything?

At a glance your client.log looks fine :)

**Comment by Marstead** [comment]
Oh, I *only* hear the default sounds, not the specified sounds at all. You're saying just switch Normal to Improved Reflexes and swing at something? I'll give it a try shortly.

**Comment by Marstead** [comment]
Oh wow yeah I do hear it now. I'll close the issue, thank you. It must be that the default sounds are loud enough and Tinder Strike is subtle enough that I couldn't hear the difference. Thanks for the help!

**Comment by Ferrariic** [comment]
> Oh, I *only* hear the default sounds, not the specified sounds at all. You're saying just switch Normal to Improved Reflexes and swing at something? I'll give it a try shortly.

Right, let me know if you hear anything at all. Could you send a picture of your volume settings in game as well? Tyvm for helping me debug this.

**Comment by Marstead** [comment]
> > Oh, I _only_ hear the default sounds, not the specified sounds at all. You're saying just switch Normal to Improved Reflexes and swing at something? I'll give it a try shortly.
> 
> Right, let me know if you hear anything at all. Could you send a picture of your volume settings in game as well? Tyvm for helping me debug this.

My in-game SFX volume is quite low. So the default sound was loud enough to drown out your sound, so that was my issue. Thanks again!
